### ISSUE TITLE
tis 브랜치에 giganto cluster 기능이 포함되도록 작업

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#674]
current tis version : 0.15.4+tis.0.0.1
target next tis version : 0.19.0+tis.0.1.0

위와 같은 상태를 만들기 위한 작업을 수행합니다.

### Task To do
- [x] 0.15.4+tis.0.0.1 가 태깅되었던 브랜치의 커밋과 히스토리를 보존하기 위해 기존 `tis` 브랜치를 `archive/0.15.4+tis.0.0.1` 으로 rename
- [x] 0.19.0 에서 `tis` 브랜치 다시 신규 생성
- [x] 0.19.0을 베이스로 하는  0.19.0+tis.0.1.0-alpha.1 생성하여서 PR

--- 
### 폐기된 이슈 초안 (deprecate, https://github.com/aicers/giganto/issues/674#issuecomment-1953497626 에서의 논의 참고)

이를 위한 rebase 작업을 합니다. (tis 브랜치의 기존 히스토리가 변경되는 push force 를 수반합니다.)
- [x] rebase 작업 : https://github.com/sophie-cluml/giganto/commits/sophie/tis/rebase-upon-0.18.0/
~- [] push-force to `tis~

기타 아이디어
- 0.15.4+tis.0.0.1 가 태깅되었던 브랜치의 커밋과 히스토리를 보존하기 위해 기존 `tis` 브랜치를 `archive/0.15.4+tis.0.0.1` 과 같이 남겨놓는 작업을 진행

**Comment by sophie-cluml** [comment]
@sehkone rebase는 tis 브랜치의 기존 히스토리가 변경되는 push force 를 추후 수반하게 됩니다. 프로젝트 버전 관리 가이드 작성 당시 저는 놓쳤던 부분이라서, rebase로 진행해도 문제없을지 컨펌 부탁드립니다.

**Comment by sehkone** [comment]
> 기타 아이디어에 대해서도 의견 부탁드립니다.
@sophie-cluml
위에 작성해 놓은 "기타 아이디어" 방식이 좋을 것 같습니다.

**Comment by sophie-cluml** [comment]
dependent to #691
