### ISSUE TITLE
Heavy traffic 환경에서 Giganto가 Export한 이벤트 파일을 Web UI에서 다운로드하는 방법

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#694]
## 이슈
프로젝트 Tis와 같이 트래픽이 너무 많아 가급적 Giganto의 부담을 줄여야하는 환경에서 고객의 요구사항 - `Web UI에서 Export한 이벤트 파일을 다운로드할 수 있게 해주시오` - 을 만족하기 위한 아이디어입니다.

Export 기능 자체는 건드릴 수 없지만, Export된 파일을 Giganto -> REview -> Web UI로 전송하는 경로에서 Giganto의 부담을 줄여보려고 합니다.

## 제안
사용자가 Web UI를 통해서 Export 파일을 다운로드 요청하면, REview가 SCP를 이용해서 Giganto 서버로부터 해당 파일을 로컬 서버로 복사하고, 이후 Web UI에서 사용자에게 다운로드합니다. Giganto는 Export 파일을 REview에게 전송하는 과정에서 제외되므로 부담을 줄일 수 있습니다.

## Tasks
- [ ] Export가 완료되었는지 알 수 있도록 작업 중에는 파일이름에 `.export` 태그를 붙이고, 완료 후 `.export` 태그를 없앤다.
- [ ] Export 파일 목록 및 상태 조회 요청을 처리하는 GraphQL API 추가
  Giganto 장비별로 Export가 진행중인 파일 목록과 완료된 파일 목록을 구분하여 UI에게 리턴하는 GraphQL API를 추가한다.
- [ ] REview의 작업: (이 방법으로 개발을 진행한다면 이번 항목은 REview-web으로 이동할 예정입니다.)
  REview는 Export 파일 다운로드 요청을 받으면 SCP를 이용해서 Giganto 장비로부터 파일을 복사하고, Web UI에 그 경로를 리턴한다. Web UI는 리턴 받은 경로의 파일을 사용자가 다운로드하는 기능을 개발한다.

**Comment by syncpark** [comment]
@MW-Kim @sophie-cluml @kimhanbeom 이 방법 어떤지 의견을 부탁합니다.

**Comment by kimhanbeom** [comment]
다운로드 요청을 통해 Giganto에서 REview로 파일을 복사할 경우, 다운로드 경로는 바로 리턴이 되나 실제 파일의 다운로드는 파일의 크기에 따라 시간이 더 걸릴 수 있다고 생각됩니다. scp가 완료 된 후에 Web UI측에서 개발한 파일 다운로드 기능을 사용하기 위해서 REview에도 추가적으로 scp 진행/완료에 대한 확인 할 수 있는 추가 기능이 필요할 것으로 보입니다.

**Comment by syncpark** [comment]
Web UI와 REview 사이에서 UI를 통한 파일 다운로드를 어떻게 지원할거냐에 대한 내용이 빠졌네요. 이 부분은 REview에 이슈를 올리거나 개발할 때 고려가 필요할 것 같습니다.

다만, 간단한 아이디어로 scp를 사용할 때도 저장하는 파일 이름 뒤에 `.download` 태그를 붙이고, 다운로드가 완료되면 태그를 없애는 방식으로 구현하면 되겠네요.

**Comment by sophie-cluml** [comment]
요구조건 상, 제1목표와 제2목표가 있다고 이해하였습니다.
- 제1목표(선순위목표): Export된 이벤트 파일을 Web UI에서 다운로드하는 기능 (고객요구)
- 제2목표(후순위목표): 최대한 giganto에게 network i/o 부담을 적게 준다 (성능고려)

최초 제안주신 아래 2개는 제1목표를 잘 달성하는 좋은 아이디어인 것 같습니다.
>  - Export가 완료되었는지 알 수 있도록 작업 중에는 파일이름에 .export 태그를 붙이고, 완료 후 .export 태그를 없앤다.
> - Export 파일 목록 및 상태 조회 요청을 처리하는 GraphQL API 추가
  Giganto 장비별로 Export가 진행중인 파일 목록과 완료된 파일 목록을 구분하여 UI에게 리턴하는 GraphQL API를 추가한다.

다만 scp도 giganto의 network i/o를 소모하는 것은 마찬가지라고 보여서 review가 데이터를 들고 있는것이 고객관점 또는 성능관점에서 추가적인 이득이 있는지 궁금합니다.

**Comment by sophie-cluml** [comment]
gignato 스스로 해결할 수 있는 network i/o 개선 및 추가적인 resource 사용효율 개선은 다음과 같은 것이 있는 것 같아요
- export 파일을 plain .csv, .json 가 아닌, 압축파일로 저장 => 결과적으로 network bandwidth 소모량을 감소
- export가 line by line으로 file write 하고 있는 것을 약 100~200 라인 단위(적절한 수치는 따로 찾아야함)로 bulk write => file i/o 개선

**Comment by sophie-cluml** [comment]
한편, cluster 환경을 고려할 때에, giganto1 <-> giganto2 간 에 대용량의 파일이 오가는 것은 network bandwidth를 잡아먹는 일일 것 같아서, 이 부분 peer 간 통신은 스킵하고 직접 파일 들고 있는 giganto와 통신할 수 있도록 고려가 필요할 것 같아요.

**Comment by sehkone** [comment]
@syncpark Giganto가 export 하는 부분은 완료가 되었나요?

**Comment by sehkone** [comment]
@syncpark @sophie-cluml @MW-Kim,
브라우저 즉 UI에서 export 된 파일을 다운받는 것은 현재 고객과 협의를 통하여 요구 사항에서 제외가 되었으니, 이 이슈는 닫도록 하겠습니다.
