### ISSUE TITLE
tis 브랜치에 0.20.0까지의 기능이 포함되도록 작업

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#746]
current tis version : 0.19.0+tis.0.1.0
target next tis version : 0.20.0+tis.0.2.0

### Task To do
- [x] 0.19.0+tis.0.1.0 가 태깅되었던 브랜치의 커밋과 히스토리를 보존하기 위해 기존 `tis` 브랜치를 `archive/0.19.0+tis.0.1.0` 으로 rename
- [x] 0.20.0 에서 `tis` 브랜치 다시 신규 생성
- [x] 0.20.0을 베이스로 하는  0.20.0+tis.0.2.0-alpha.1 생성하여서 PR

**Comment by kimhanbeom** [comment]
해당 이슈 완료되어 close합니다.
